#!/usr/bin/env python3
"""Generate a double-blind review draft from the author-labeled manuscript."""
from __future__ import annotations

import re
import sys
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent.parent
PAPER_DIR = PROJECT_ROOT / "paper_latex"
SOURCE = PAPER_DIR / "resource_nmcts_submission_v1.tex"
ANONYMOUS_SOURCE = PAPER_DIR / "resource_nmcts_submission_anonymous.tex"

ANONYMOUS_AVAILABILITY = r"""\section*{Data and Code Availability}

For double-blind review, the artifact archive should be supplied through the
selected venue's anonymous review system or through a venue-approved anonymous
repository link.  This generated review draft intentionally omits
author-identifying repository paths and final archive identifiers.  The
non-anonymous artifact package records the exact scripts, tables, raw CSV
files, manifests, and rebuild commands; these materials should be released
with the final public archive after review.

"""


def anonymize(text: str) -> str:
    text = re.sub(
        r"\\author\{[^{}]*\}",
        r"\\author{Anonymous Authors}",
        text,
        count=1,
    )
    text = re.sub(
        r"\\section\*\{Data and Code Availability\}.*?(?=\\bibliographystyle)",
        lambda _match: ANONYMOUS_AVAILABILITY,
        text,
        count=1,
        flags=re.DOTALL,
    )
    marker = "% Generated by make_anonymous_review_draft.py; do not edit manually.\n"
    if marker not in text:
        text = text.replace("\\documentclass[11pt]{article}\n", "\\documentclass[11pt]{article}\n" + marker, 1)
    return text


def validate(text: str) -> list[str]:
    issues: list[str] = []
    if r"\author{Anonymous Authors}" not in text:
        issues.append("anonymous author field missing")
    if "Zixiang Zhou" in text:
        issues.append("author name still present")
    if "resource\\_nmcts\\_experiment" in text or "resource_nmcts_experiment" in text:
        section = re.search(
            r"\\section\*\{Data and Code Availability\}(.*?)(?:\\bibliographystyle|\Z)",
            text,
            flags=re.DOTALL,
        )
        if section and ("resource\\_nmcts\\_experiment" in section.group(1) or "resource_nmcts_experiment" in section.group(1)):
            issues.append("repository-relative availability path still present")
    if "anonymous review" not in text.lower():
        issues.append("anonymous review wording missing")
    return issues


def main() -> int:
    source = SOURCE.read_text(encoding="utf-8")
    anonymous = anonymize(source)
    issues = validate(anonymous)
    if issues:
        for issue in issues:
            print(f"error: {issue}", file=sys.stderr)
        return 1
    ANONYMOUS_SOURCE.write_text(anonymous, encoding="utf-8")
    print(f"wrote {ANONYMOUS_SOURCE.relative_to(PROJECT_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
