#!/usr/bin/env python3
"""Audit manuscript figure assets and source-data linkage.

The submission includes generated figures in PDF/PNG/SVG form plus source-data
CSVs.  This audit checks that every figure referenced by the author and
anonymous manuscripts is generated by the figure script, has all expected asset
formats, and carries non-empty plotted source data.
"""
from __future__ import annotations

import csv
import json
import re
import subprocess
import sys
from pathlib import Path


THIS_DIR = Path(__file__).resolve().parent
RESULTS = THIS_DIR / "results"
FIGURES = THIS_DIR / "paper_latex" / "figures" / "submission_v36"
SOURCE_DATA = FIGURES / "source_data"
AUTHOR_TEX = THIS_DIR / "paper_latex" / "resource_nmcts_submission_v1.tex"
ANON_TEX = THIS_DIR / "paper_latex" / "resource_nmcts_submission_anonymous.tex"
FIGURE_SCRIPT = THIS_DIR / "make_submission_figures.py"


def rel(path: Path) -> str:
    return str(path.relative_to(THIS_DIR))


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8") if path.exists() else ""


def includegraphics_bases(path: Path) -> list[str]:
    text = read_text(path)
    bases: list[str] = []
    for match in re.finditer(r"\\includegraphics(?:\[[^\]]*\])?\{([^{}]+)\}", text):
        figure = Path(match.group(1)).name
        if figure.startswith("fig"):
            bases.append(Path(figure).stem)
    return bases


def generated_bases() -> tuple[set[str], set[str]]:
    text = read_text(FIGURE_SCRIPT)
    saved = set(re.findall(r"save\(fig,\s*\"([^\"]+)\"\)", text))
    sourced = set(re.findall(r"write_source\(\s*\"([^\"]+)\"", text, flags=re.DOTALL))
    return saved, sourced


def pdf_pages(path: Path) -> str:
    if not path.exists():
        return "missing"
    try:
        proc = subprocess.run(
            ["pdfinfo", str(path)],
            check=False,
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            text=True,
            timeout=8,
        )
    except Exception:
        return "unknown"
    match = re.search(r"^Pages:\s+(\d+)", proc.stdout, flags=re.MULTILINE)
    return match.group(1) if match else "unknown"


def csv_row_count(path: Path) -> int:
    if not path.exists():
        return -1
    with path.open("r", newline="", encoding="utf-8") as f:
        reader = csv.reader(f)
        rows = list(reader)
    return max(len(rows) - 1, 0) if rows else -1


def file_ok(path: Path, min_bytes: int, magic: bytes | None = None, token: str | None = None) -> bool:
    if not path.exists() or path.stat().st_size < min_bytes:
        return False
    if magic is not None and not path.read_bytes().startswith(magic):
        return False
    if token is not None and token not in path.read_text(encoding="utf-8", errors="replace"):
        return False
    return True


def build_rows() -> list[dict[str, str]]:
    author_refs = includegraphics_bases(AUTHOR_TEX)
    anon_refs = includegraphics_bases(ANON_TEX)
    saved, sourced = generated_bases()
    bases = sorted(set(author_refs) | set(anon_refs) | saved | sourced)
    rows: list[dict[str, str]] = []
    for base in bases:
        pdf = FIGURES / f"{base}.pdf"
        png = FIGURES / f"{base}.png"
        svg = FIGURES / f"{base}.svg"
        source = SOURCE_DATA / f"{base}.csv"
        pages = pdf_pages(pdf)
        source_rows = csv_row_count(source)
        checks = {
            "author_ref": base in author_refs,
            "anonymous_ref": base in anon_refs,
            "script_save": base in saved,
            "script_source": base in sourced,
            "pdf": pages == "1" and file_ok(pdf, 1000, magic=b"%PDF"),
            "png": file_ok(png, 1000, magic=b"\x89PNG\r\n\x1a\n"),
            "svg": file_ok(svg, 1000, token="<svg"),
            "source_csv": source_rows > 0,
        }
        missing = [name for name, ok in checks.items() if not ok]
        rows.append(
            {
                "figure": base,
                "status": "pass" if not missing else "needs revision",
                "author_ref": str(checks["author_ref"]),
                "anonymous_ref": str(checks["anonymous_ref"]),
                "script_save": str(checks["script_save"]),
                "script_source": str(checks["script_source"]),
                "pdf_pages": pages,
                "pdf_bytes": str(pdf.stat().st_size if pdf.exists() else 0),
                "png_bytes": str(png.stat().st_size if png.exists() else 0),
                "svg_bytes": str(svg.stat().st_size if svg.exists() else 0),
                "source_rows": str(source_rows),
                "missing": ", ".join(missing) if missing else "none",
                "next_action": "Regenerate figures with make_submission_figures.py and keep TeX references aligned with source_data CSVs.",
            }
        )
    return rows


def write_csv(path: Path, rows: list[dict[str, str]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fields = [
        "figure",
        "status",
        "author_ref",
        "anonymous_ref",
        "script_save",
        "script_source",
        "pdf_pages",
        "pdf_bytes",
        "png_bytes",
        "svg_bytes",
        "source_rows",
        "missing",
        "next_action",
    ]
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fields, lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)


def write_markdown(path: Path, rows: list[dict[str, str]]) -> None:
    counts: dict[str, int] = {}
    for row in rows:
        counts[row["status"]] = counts.get(row["status"], 0) + 1
    lines = [
        "# Figure Asset Audit",
        "",
        "This audit checks manuscript figure references, generated PDF/PNG/SVG assets, and plotted source-data CSV files.",
        "",
        "## Status counts",
        "",
    ]
    for status in sorted(counts):
        lines.append(f"- {status}: {counts[status]}")
    lines.extend(
        [
            "",
            "| figure | status | refs | generated | bytes pdf/png/svg | source rows | missing |",
            "|---|---|---|---|---:|---:|---|",
        ]
    )
    for row in rows:
        refs = f"author={row['author_ref']}; anon={row['anonymous_ref']}"
        generated = f"save={row['script_save']}; source={row['script_source']}; pages={row['pdf_pages']}"
        byte_text = f"{row['pdf_bytes']}/{row['png_bytes']}/{row['svg_bytes']}"
        lines.append(
            f"| {row['figure']} | {row['status']} | {refs} | {generated} | {byte_text} | {row['source_rows']} | {row['missing']} |"
        )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_manifest(path: Path, rows: list[dict[str, str]]) -> None:
    counts = {status: sum(1 for row in rows if row["status"] == status) for status in sorted({row["status"] for row in rows})}
    data = {
        "script": Path(__file__).name,
        "python": sys.version.split()[0],
        "figures": len(rows),
        "needs_revision_count": counts.get("needs revision", 0),
        "status_counts": counts,
        "formats_required": ["pdf", "png", "svg", "source_csv"],
        "source_files": {
            "author_tex": rel(AUTHOR_TEX),
            "anonymous_tex": rel(ANON_TEX),
            "figure_script": rel(FIGURE_SCRIPT),
            "figure_dir": rel(FIGURES),
            "source_data_dir": rel(SOURCE_DATA),
        },
        "outputs": {
            "summary": "results/summary_figure_asset_audit.csv",
            "analysis": "results/analysis_figure_asset_audit.md",
            "manifest": "results/manifest_figure_asset_audit.json",
        },
    }
    path.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def main() -> int:
    rows = build_rows()
    write_csv(RESULTS / "summary_figure_asset_audit.csv", rows)
    write_markdown(RESULTS / "analysis_figure_asset_audit.md", rows)
    write_manifest(RESULTS / "manifest_figure_asset_audit.json", rows)
    failures = sum(1 for row in rows if row["status"] == "needs revision")
    print(f"wrote {len(rows)} figure asset audit row(s)")
    if failures:
        print(f"warning: {failures} figure asset row(s) need revision")
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
